filetype plugin indent on
syntax on
set nu
colorscheme ron

" tab settings
set autoindent
set tabstop=2
set expandtab
set shiftwidth=2
set smartindent

" search
set incsearch
set hlsearch
set ignorecase
set smartcase

" quality of life
set hidden
set nobackup
set nowritebackup
set updatetime=300
set signcolumn=number

" hit \pp to toggle paste mode
noremap <leader>pp :set invpaste<cr>

" project-local .vimrc, safely
set exrc
set secure

" fugitive (git inside vim) is cloned into the pack dir at image build time.
