# lemma -> emoji hints, deterministic, no AI.
# First matching lemma in a chunk wins (chunk.py). Keep entries lowercase.

_EN = {
    # animals
    "wolf": "🐺", "lamb": "🐑", "sheep": "🐑", "lion": "🦁", "fox": "🦊",
    "mouse": "🐭", "cat": "🐱", "kitten": "🐱", "dog": "🐶", "bird": "🐦",
    "rabbit": "🐰", "hare": "🐰", "horse": "🐴", "ass": "🫏", "donkey": "🫏",
    "ox": "🐂", "bull": "🐂", "cow": "🐄", "goat": "🐐", "pig": "🐷",
    "swine": "🐷", "frog": "🐸", "snake": "🐍", "serpent": "🐍",
    "eagle": "🦅", "hawk": "🦅", "crow": "🐦‍⬛", "raven": "🐦‍⬛",
    "cock": "🐓", "rooster": "🐓", "hen": "🐔", "goose": "🪿", "swan": "🦢",
    "duck": "🦆", "owl": "🦉", "bear": "🐻", "boar": "🐗", "stag": "🦌",
    "deer": "🦌", "monkey": "🐒", "ape": "🐒", "camel": "🐫",
    "elephant": "🐘", "tortoise": "🐢", "turtle": "🐢", "crab": "🦀",
    "fish": "🐟", "bee": "🐝", "ant": "🐜", "fly": "🪰", "spider": "🕷️",
    "grasshopper": "🦗", "bat": "🦇", "mole": "🦔", "weasel": "🦡",
    "kid": "🐐", "fowl": "🐔", "dove": "🕊️", "pigeon": "🕊️",
    "caterpillar": "🐛", "worm": "🪱", "dragon": "🐉", "mule": "🫏",
    # people
    "king": "👑", "queen": "👑", "prince": "🤴", "princess": "👸",
    "man": "👨", "woman": "👩", "boy": "👦", "girl": "👧", "child": "🧒",
    "mother": "👩‍🍼", "father": "👨", "sister": "👧", "brother": "👦",
    "baby": "👶", "farmer": "🧑‍🌾", "shepherd": "🧑‍🌾", "fisherman": "🎣",
    "hunter": "🏹", "soldier": "💂", "thief": "🥷", "doctor": "🧑‍⚕️",
    "friend": "🤝", "enemy": "⚔️", "traveler": "🧳", "traveller": "🧳",
    "witch": "🧙", "giant": "🗿", "god": "⚡", "duchess": "👸",
    # nature
    "sun": "☀️", "moon": "🌙", "star": "⭐", "sky": "🌌", "sea": "🌊",
    "river": "🏞️", "water": "💧", "rain": "🌧️", "snow": "❄️", "wind": "🌬️",
    "storm": "⛈️", "fire": "🔥", "tree": "🌳", "forest": "🌲", "wood": "🌲",
    "flower": "🌸", "rose": "🌹", "grass": "🌿", "mountain": "⛰️",
    "stone": "🪨", "rock": "🪨", "earth": "🌍", "night": "🌃", "day": "🌤️",
    "winter": "☃️", "summer": "😎", "spring": "🌷", "garden": "🌷",
    "field": "🌾", "corn": "🌽", "grape": "🍇", "apple": "🍎",
    # objects & places
    "house": "🏠", "home": "🏠", "door": "🚪", "key": "🔑", "table": "🪑",
    "book": "📖", "letter": "✉️", "gold": "💰", "money": "💰", "coin": "🪙",
    "treasure": "💎", "jewel": "💎", "ring": "💍", "crown": "👑",
    "sword": "🗡️", "axe": "🪓", "arrow": "🏹", "trap": "🪤", "net": "🕸️",
    "boat": "⛵", "ship": "⛵", "cart": "🛒", "road": "🛣️", "way": "🛤️",
    "bridge": "🌉", "well": "🕳️", "pot": "🍲", "cup": "🍵", "tea": "🍵",
    "bread": "🍞", "cheese": "🧀", "meat": "🍖", "honey": "🍯",
    "milk": "🥛", "egg": "🥚", "wine": "🍷", "dinner": "🍽️", "supper": "🍽️",
    "food": "🍽️", "cake": "🍰", "bottle": "🍾", "clock": "🕰️",
    "watch": "⌚", "candle": "🕯️", "lamp": "🪔", "bed": "🛏️",
    "clothes": "👗", "shoe": "👞", "hat": "🎩", "glove": "🧤",
    "mirror": "🪞", "window": "🪟", "wall": "🧱", "tower": "🗼",
    "castle": "🏰", "palace": "🏰", "church": "⛪", "market": "🏪",
    "village": "🏘️", "town": "🏘️", "city": "🏙️", "hole": "🕳️",
    # actions & states
    "eat": "🍽️", "drink": "🥤", "run": "🏃", "walk": "🚶", "jump": "🤸",
    "fall": "🫳", "fly": "🕊️", "swim": "🏊", "sleep": "😴", "dream": "💭",
    "wake": "⏰", "cry": "😢", "weep": "😢", "laugh": "😂", "smile": "😊",
    "sing": "🎵", "dance": "💃", "play": "🎲", "fight": "🤺", "kill": "💀",
    "die": "💀", "death": "💀", "dead": "💀", "love": "❤️", "kiss": "💋",
    "marry": "💒", "hate": "💢", "fear": "😨", "afraid": "😨",
    "angry": "😠", "anger": "😠", "happy": "😊", "sad": "😢",
    "hungry": "😋", "thirsty": "🥤", "tired": "🥱", "cold": "🥶",
    "hot": "🥵", "sick": "🤒", "beautiful": "✨", "pretty": "✨",
    "ugly": "🫣", "old": "👴", "young": "🌱", "big": "🐘", "little": "🤏",
    "small": "🤏", "great": "🌟", "poor": "🪙", "rich": "💰",
    "strong": "💪", "weak": "🍃", "wise": "🦉", "foolish": "🤡",
    "speak": "🗣️", "say": "💬", "tell": "💬", "ask": "❓", "answer": "💬",
    "shout": "📢", "whisper": "🤫", "hear": "👂", "listen": "👂",
    "see": "👀", "look": "👀", "watch": "👀", "find": "🔍", "seek": "🔍",
    "hide": "🙈", "steal": "🥷", "give": "🎁", "gift": "🎁", "take": "🫴",
    "think": "🤔", "know": "💡", "learn": "📚", "read": "📖",
    "write": "✍️", "work": "🔨", "help": "🆘", "save": "🛟",
    "promise": "🤞", "wish": "🌠", "magic": "✨", "curse": "🌩️",
    "time": "⏳", "year": "📅", "morning": "🌅", "evening": "🌆",
    "heart": "❤️", "eye": "👁️", "hand": "✋", "foot": "🦶", "head": "🗣️",
    "voice": "🗣️", "tail": "〰️", "wing": "🪽", "golden": "✨",
}

_DE = {
    # tiere
    "wolf": "🐺", "lamm": "🐑", "schaf": "🐑", "löwe": "🦁", "fuchs": "🦊",
    "maus": "🐭", "katze": "🐱", "kätzchen": "🐱", "hund": "🐶",
    "vogel": "🐦", "vöglein": "🐦", "hase": "🐰", "kaninchen": "🐰",
    "pferd": "🐴", "esel": "🫏", "ochse": "🐂", "stier": "🐂", "kuh": "🐄",
    "ziege": "🐐", "geiß": "🐐", "schwein": "🐷", "frosch": "🐸",
    "schlange": "🐍", "adler": "🦅", "habicht": "🦅", "krähe": "🐦‍⬛",
    "rabe": "🐦‍⬛", "hahn": "🐓", "huhn": "🐔", "henne": "🐔",
    "gans": "🪿", "schwan": "🦢", "ente": "🦆", "eule": "🦉", "bär": "🐻",
    "eber": "🐗", "hirsch": "🦌", "reh": "🦌", "affe": "🐒",
    "kamel": "🐫", "elefant": "🐘", "schildkröte": "🐢", "krebs": "🦀",
    "fisch": "🐟", "biene": "🐝", "ameise": "🐜", "fliege": "🪰",
    "spinne": "🕷️", "fledermaus": "🦇", "taube": "🕊️", "wurm": "🪱",
    "drache": "🐉", "storch": "🦩", "zicklein": "🐐",
    # menschen
    "könig": "👑", "königin": "👑", "prinz": "🤴", "prinzessin": "👸",
    "königssohn": "🤴", "königstochter": "👸",
    "mann": "👨", "frau": "👩", "junge": "👦", "knabe": "👦",
    "mädchen": "👧", "kind": "🧒", "mutter": "👩‍🍼", "vater": "👨",
    "schwester": "👧", "bruder": "👦", "großmutter": "👵",
    "großvater": "👴", "baby": "👶", "bauer": "🧑‍🌾", "hirte": "🧑‍🌾",
    "fischer": "🎣", "jäger": "🏹", "soldat": "💂", "dieb": "🥷",
    "räuber": "🥷", "arzt": "🧑‍⚕️", "freund": "🤝", "feind": "⚔️",
    "hexe": "🧙", "zwerg": "🧝", "riese": "🗿", "müller": "🌾",
    "schneider": "🪡", "schuster": "👞", "braut": "👰",
    "bräutigam": "🤵", "stiefmutter": "🧙",
    # natur
    "sonne": "☀️", "mond": "🌙", "stern": "⭐", "himmel": "🌌",
    "meer": "🌊", "see": "🌊", "fluss": "🏞️", "bach": "🏞️",
    "wasser": "💧", "regen": "🌧️", "schnee": "❄️", "wind": "🌬️",
    "sturm": "⛈️", "feuer": "🔥", "baum": "🌳", "wald": "🌲",
    "holz": "🪵", "blume": "🌸", "rose": "🌹", "gras": "🌿",
    "berg": "⛰️", "stein": "🪨", "erde": "🌍", "nacht": "🌃",
    "tag": "🌤️", "winter": "☃️", "sommer": "😎", "frühling": "🌷",
    "garten": "🌷", "feld": "🌾", "korn": "🌾", "apfel": "🍎",
    # dinge & orte
    "haus": "🏠", "häuschen": "🏠", "heim": "🏠", "tür": "🚪",
    "schlüssel": "🔑", "tisch": "🪑", "buch": "📖", "brief": "✉️",
    "gold": "💰", "geld": "💰", "münze": "🪙", "schatz": "💎",
    "edelstein": "💎", "ring": "💍", "krone": "👑", "schwert": "🗡️",
    "axt": "🪓", "pfeil": "🏹", "falle": "🪤", "netz": "🕸️",
    "boot": "⛵", "schiff": "⛵", "wagen": "🛒", "weg": "🛤️",
    "straße": "🛣️", "brücke": "🌉", "brunnen": "🕳️", "topf": "🍲",
    "tasse": "🍵", "brot": "🍞", "käse": "🧀", "fleisch": "🍖",
    "honig": "🍯", "milch": "🥛", "ei": "🥚", "wein": "🍷",
    "essen": "🍽️", "kuchen": "🍰", "flasche": "🍾", "uhr": "🕰️",
    "kerze": "🕯️", "lampe": "🪔", "bett": "🛏️", "kleid": "👗",
    "schuh": "👞", "hut": "🎩", "spiegel": "🪞", "fenster": "🪟",
    "mauer": "🧱", "wand": "🧱", "turm": "🗼", "schloss": "🏰",
    "palast": "🏰", "kirche": "⛪", "markt": "🏪", "dorf": "🏘️",
    "stadt": "🏙️", "loch": "🕳️", "goldstück": "💰",
    # tun & sein
    "trinken": "🥤", "laufen": "🏃", "rennen": "🏃", "gehen": "🚶",
    "springen": "🤸", "fallen": "🫳", "fliegen": "🕊️", "schwimmen": "🏊",
    "schlafen": "😴", "träumen": "💭", "traum": "💭", "wachen": "⏰",
    "weinen": "😢", "lachen": "😂", "lächeln": "😊", "singen": "🎵",
    "tanzen": "💃", "spielen": "🎲", "kämpfen": "🤺", "töten": "💀",
    "sterben": "💀", "tod": "💀", "tot": "💀", "lieben": "❤️",
    "liebe": "❤️", "kuss": "💋", "küssen": "💋", "heiraten": "💒",
    "hochzeit": "💒", "hassen": "💢", "fürchten": "😨", "angst": "😨",
    "furcht": "😨", "zornig": "😠", "zorn": "😠", "böse": "😠",
    "glücklich": "😊", "glück": "🍀", "traurig": "😢", "hungrig": "😋",
    "hunger": "😋", "durst": "🥤", "müde": "🥱", "kalt": "🥶",
    "heiß": "🥵", "krank": "🤒", "schön": "✨", "hässlich": "🫣",
    "alt": "👴", "jung": "🌱", "groß": "🐘", "klein": "🤏",
    "arm": "🪙", "reich": "💰", "stark": "💪", "schwach": "🍃",
    "weise": "🦉", "klug": "🦉", "dumm": "🤡", "sprechen": "🗣️",
    "sagen": "💬", "erzählen": "💬", "fragen": "❓", "antworten": "💬",
    "rufen": "📢", "schreien": "📢", "flüstern": "🤫", "hören": "👂",
    "sehen": "👀", "schauen": "👀", "finden": "🔍", "suchen": "🔍",
    "verstecken": "🙈", "stehlen": "🥷", "geben": "🎁", "geschenk": "🎁",
    "nehmen": "🫴", "denken": "🤔", "wissen": "💡", "lernen": "📚",
    "lesen": "📖", "schreiben": "✍️", "arbeiten": "🔨", "arbeit": "🔨",
    "helfen": "🆘", "retten": "🛟", "versprechen": "🤞",
    "wunsch": "🌠", "wünschen": "🌠", "zauber": "✨", "zaubern": "✨",
    "verwandeln": "✨", "fluch": "🌩️", "zeit": "⏳", "jahr": "📅",
    "morgen": "🌅", "abend": "🌆", "herz": "❤️", "auge": "👁️",
    "hand": "✋", "fuß": "🦶", "kopf": "🗣️", "stimme": "🗣️",
    "schwanz": "〰️", "flügel": "🪽", "golden": "✨",
}

EMOJI = {"en": _EN, "de": _DE}
